### ISSUE TITLE
Output issue: Calling figarch from Python 3.5

### ISSUE THREAD

**Issue by NumberChiffre** [bashtage/mfe-toolbox#1]
Hello everyone,

I am using matlab.engine to call figarch from python 3.5 and I have noticed an issue. If I run figarch from matlab using figarch([0.01 0.01 0.01],1,1), my output will return the parameters including all other outputs such as the Logarithmic Likelihood. However, if I run the exact same parameters for figarch([0.01 0.01 0.01],1,1) using python, the program will only return the parameters and nothing else.

---res.resid is just the residuals from a previous process---

```

import matlab.engine 
eng = matlab.engine.start_matlab()
eng.cd(path.expanduser('~/Documents/MATLAB/MFEToolbox/univariate'))
print(eng.figarch(eng.transpose(matlab.double(res.resid.T.values.tolist())), 1, 1, 'SKEWT'))

```

In addition, if I try to include starting values for the parameters used in figarch, there is a small bug in the figarch_starting_values.m for the case of non-empty startingvals (where an additional parameter 'o' is undefined). 

I am sure that figarch should return all outputs as indicated in the documentation in either Matlab or calling from Python, I don't know what I missed. 

Would really really appreciate if someone can shed some light!!!

Thank you!

Sincerely,
Terence

**Comment by bashtage** [comment]
I only use MATLAB from MATLAB, so I can't help you on this.  Maybe StackOverflow would be a better place to get help on this issue.

Thanks for reporting the other issue.

**Comment by bashtage** [comment]
https://github.com/bashtage/mfe-toolbox/blob/master/univariate/figarch.m#L1

Shows that there are many outputs returns from figarch. 

However, note here

https://github.com/bashtage/mfe-toolbox/blob/master/univariate/figarch.m#L216

where many outputs are not produced unless specifically requested.  Maybe you can set nargout in the engine.

**Comment by NumberChiffre** [comment]
Hello Professor Sheppard,

Thank you for letting me know! I had forgotten to include the nargout argument, it turned out to be fine using matlab.engine to call figarch from python.
