### ISSUE TITLE
Output issue on Figarch.m file

### ISSUE THREAD

**Issue by alecelani94** [bashtage/mfe-toolbox#3]
Hello everyone,
I'm using the functions on MFE Toolbox in order to estimate a FIGARCH. There is a problem in line 223: the command 'robustvcv' no longer exists, so if you compute the function figarch with more than 3 nargouts returns an error. The ouputs VCV, robustVCV are necessary to infer the model and assess the robustness of the estimation.

>>if nargout>3
>>    nw=0; %No newey west on scores
>>    [VCVrobust,A,B,scores,hess]=robustvcv('figarch_likelihood',parameters,nw,
>>    p,q,epsilon,epsilon2Augmented,truncLag,errorType);
>>    T = size(epsilon,1);
>>    VCV=hess^(-1)/T;
>>end

Would really really appreciate if someone can help me.

Thank you!

Sincerely,
Alessandro

**Comment by bashtage** [comment]
This file is in the folder utility:

https://github.com/bashtage/mfe-toolbox/tree/master/utility

You need to ensure all of the toolbox is on your path.

**Comment by alecelani94** [comment]
Thank you for your immediate response, Professor Sheppard. I should have looked more carefully at all the components of the toolbox.
